### PR TITLE
sending encrypted direct messages (nip04) with noscl

### PR DESCRIPTION
**Pull request by raphjaph**
Wanted to send a direct message with `noscl` and noticed that this was not supported. I have an open PR in the upstream `go-nostr` module/library that implements the basic nip04 functions (shared key generation, encryption, decryption). This PR can't be merged until the upstream merges and releases a new version. 

I have no idea if this is the best way to do this, so just let me know if this is the wrong approach.

### CODE REVIEW

**Comment by fiatjaf** [comment]
Does this work? I want to merge but I don't want to test it myself right now.

**Comment by raphjaph** [comment]
It can work like this if you change the go.mod require for `go-nostr` to:
~~github.com/fiatjaf/go-nostr v0.5.0~~
github.com/fiatjaf/go-nostr  v0.5.1-0.20220206131609-7760f53ce28a

You would have to get the package by referencing the master branch.
`go get github.com/fiatjaf/go-nostr@master` 

It is probably cleaner and easier to tag this commit as a new version (v0.5.1) and then just do:
~~github.com/fiatjaf/go-nostr v0.5.0~~
github.com/fiatjaf/go-nostr  v0.5.1

**Comment by raphjaph** [comment]
*It is probably cleaner and easier to tag the nip04 commit in `go nostr` as a new version (v0.5.1) and then just do:
github.com/fiatjaf/go-nostr v0.5.0
github.com/fiatjaf/go-nostr v0.5.1

**Comment by raphjaph** [comment]
When you've done that I can update the `go.mod` file, try building `noscl` and the update this PR

**Comment by fiatjaf** [comment]
You can also add a "replace" thing on your local `go.mod` to reference a local package and bypass the version tags.

Anyway, I've published go-nostr v0.5.1 now.

**Comment by raphjaph** [comment]
Perfect, thanks! 

I was able to to build this on macOS and on a debian machine. So I think this should work now.

**Comment by honza** [comment]
Please clean up the git history, if you don't mind.

**Comment by raphjaph** [comment]
Ok, I really have to learn how to rebase forked repos. The commit history should look cleaner now. Let me know if this is what you were looking for.

**Comment by honza** [comment]
Thanks

**Comment by honza** [comment]
LGTM

**Pull request merged**
