### PR TITLE
Add setprivate to Usage

### PR DESCRIPTION
**Pull request by garyray-k**

### CODE REVIEW

**Comment by fiatjaf** [comment]
Thank you, but it is already there on `main.go`. Can you add it just to the README?

**Comment by garyray-k** [comment]
My mistake. Corrected.

**Comment by garyray-k** [comment]
Nvm. It's there too. Closing.

**Comment by garyray-k** [comment]
☕️soon...

**Comment by fiatjaf** [comment]
ahahah

**Pull request closed without merging**
